# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

variables:
  DIFF_COVER_CHECK_THRESHOLD: 80
  DIFF_COVER_ENABLE: 'true'
  DIFF_COVER_WORKING_DIRECTORY: $(System.DefaultWorkingDirectory)
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    BRANCH_NAME: $(System.PullRequest.TargetBranch)
  ${{ else }}:
    BRANCH_NAME: $(Build.SourceBranchName)


pool:
  vmImage: 'ubuntu-20.04'

container:
  image: sonicdev-microsoft.azurecr.io:443/sonic-slave-bullseye:latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    source: specific
    project: build
    pipeline: 142
    artifact: sonic-buildimage.vs
    runVersion: 'latestFromBranch'
    runBranch: 'refs/heads/$(BRANCH_NAME)'
  displayName: "Download artifacts from latest sonic-buildimage build"

- script: |
    set -xe
    sudo apt-get -y purge libhiredis-dev libnl-3-dev libnl-route-3-dev
    sudo dpkg -i libyang_1.0.73_amd64.deb \
                 libnl-3-200_*.deb \
                 libnl-genl-3-200_*.deb \
                 libnl-route-3-200_*.deb \
                 libnl-nf-3-200_*.deb \
                 libhiredis0.14_*.deb \
                 libswsscommon_1.0.0_amd64.deb \
                 python3-swsscommon_1.0.0_amd64.deb
  workingDirectory: $(Pipeline.Workspace)/target/debs/bullseye/
  displayName: 'Install Debian dependencies'

- script: |
    set -xe
    sudo pip3 install swsssdk-2.0.1-py3-none-any.whl
    sudo pip3 install sonic_py_common-1.0-py3-none-any.whl
    sudo pip3 install sonic_yang_mgmt-1.0-py3-none-any.whl
    sudo pip3 install sonic_yang_models-1.0-py3-none-any.whl
    sudo pip3 install sonic_config_engine-1.0-py3-none-any.whl
  workingDirectory: $(Pipeline.Workspace)/target/python-wheels/bullseye/
  displayName: 'Install Python dependencies'

- script: |
    set -ex
    # Install .NET CORE
    curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    . /etc/os-release
    sudo apt-add-repository https://packages.microsoft.com/debian/$VERSION_ID/prod
    sudo apt-get update
    sudo apt-get install -y dotnet-sdk-5.0
  displayName: "Install .NET CORE"

# Python 3
- script: |
    python3 setup.py test
  displayName: 'Test Python 3'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
    testRunTitle: Python 3
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
  displayName: 'Publish Python 3 test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/htmlcov/'
  displayName: 'Publish Python 3 test coverage'

- script: |
    set -e
    python3 setup.py bdist_wheel
  displayName: 'Build Python 3 wheel'

- publish: '$(System.DefaultWorkingDirectory)/dist/'
  artifact: wheels
  displayName: "Publish Python wheels"
